FROM {{ IMAGE_BASE }}
MAINTAINER Michael Gebetsroither <michael@mgeb.org>

RUN set -ex \
    && echo 'deb-src http://172.17.0.1:9999/debian {{ dist_name }} main contrib non-free' >>/etc/apt/sources.list \
{%- if dist_name != "sid" %}
    && echo 'deb-src http://172.17.0.1:9999/debian {{ dist_name }}-updates main' >>/etc/apt/sources.list \
    && echo 'deb-src http://172.17.0.1:9999/debian-security {{ dist_name }}/updates main' >>/etc/apt/sources.list \
{%- endif %}
    && apt-get update -q \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y -q --no-install-recommends apt-file \
    && apt-file update

RUN set -ex \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y -q --no-install-recommends vim-nox less curl ca-certificates apt-transport-https build-essential devscripts equivs
