FROM {{ IMAGE_BASE }}
MAINTAINER Michael Gebetsroither <michael@mgeb.org>

RUN set -ex \
    && echo 'APT::Install-Recommends "false";' >/etc/apt/apt.conf.d/10own \
    && echo 'Acquire::PDiffs "false";' >>/etc/apt/apt.conf.d/10own \
    && echo 'deb http://172.17.0.1:9999/debian {{ IMAGE_DIST_NAME }} main contrib non-free' >/etc/apt/sources.list \
{%- if IMAGE_DIST_NAME != "sid" %}
    && echo 'deb http://172.17.0.1:9999/debian {{ IMAGE_DIST_NAME }}-updates main' >>/etc/apt/sources.list \
    && echo 'deb http://172.17.0.1:9999/debian-security {{ IMAGE_DIST_NAME }}/updates main' >>/etc/apt/sources.list
{%- endif %}
    && apt-get update -q \
    && apt-get upgrade -y -q

RUN set -ex \
    && apt-get install -y -q --no-install-recommends apt-file \
    && apt-file update

RUN set -ex \
    && apt-get install -y -q --no-install-recommends vim-nox curl ca-certificates apt-transport-https build-essential devscripts equivs
